### PR TITLE
Subdirectory support

### PR DESCRIPTION
**Pull request by alex0124000**
These are quite a few topics, but I have a pull request ready (works on my setup).

I have web dav server that contains several subdirectories (basically one per vacation).
These directories have names with spaces (e.g., "2016-06 Hawaii" or "2018-02 Italy") and can again have subdirectories.
They contain some videos in addition to the pictures.

I did some changes to photoframe.sh such that
1. spaces are handled
2. rsync does not copy the videos
3. only jpg, JPG, and png are counted in the get_file function

I also abused the error reporting mechanism to show the name of the current file (I would like to know whether I'm looking at Hawaii or Italy).

### CODE REVIEW

**Comment by alex0124000** [comment]
The changes in this pull request look a bit different than I expected. I only changed package/photoframe/photoframe.sh

**Comment by avanc** [comment]
@alex0124000 Thanks for you input!
I just had a look short look into your pull requests and there are some interesting ideas. I like the photo list as separate file.

Don't mind the additional commits to your pull request. I did an update of thingOS, but unortunately, it does not compile for RPi4. Thus, the Bugfix release was published on another branch. I'll handle it...

One question out of curiousity: why did you add the double quotes in the mount command?

And one remark: I think I won't show the file path by default. But I might make it configurable.

I'll work on this in the next days.

**Comment by alex0124000** [comment]
> One question out of curiousity: why did you add the double quotes in the mount command?
I think they are not necessary. The photo folder on the webdav server also has a space (like "my photos"). But I could not get the mount command to accept that. In the end, I added a new "photoframe" folder on the server.

> And one remark: I think I won't show the file path by default. But I might make it configurable.
Yes, that makes sense :) I think I will also strip the common path prefix.

**Comment by avanc** [comment]
@alex0124000 Thanks again for your input. The changes are merged and will be available in the next release. However, I have to fix some bugs before doing the next release.

**Pull request merged**
