### PR TITLE
Feature/matrix support

### PR DESCRIPTION
**Pull request by universalappfactory**
Hi,

first of all, thanks for this nice project.

Because I'am a fan of the matrix messenger protocol specfication [matrix.org](https://matrix.org) and use it as messenger,
my plan is to share the pictures via the matrix protocol instead of WebDav.
(Matrix is an open standard for secure, decentralised, real-time communication)

The idea is, that you can use any messenger which supports matrix (e.g. [element.io](https://element.io) and then you just have to create a chatroom where you want to share your pictures with other people and/or the photoframe.
The photoframe itself is just a matrix user.
If you invite the photoframe user into a chatroom, the photoframe will automatically join the room and download all pictures posted into this room.
(The photoframe will only accept room invitations and pictures from a list of trusted userids).

The matrix client also supports end-to-end encryption to securly transfer pictures.

For the matrix-client I created a python package (https://github.com/universalappfactory/matrix-photos) which is available at pypi as well (still beta).

And because I needed to install some more dependencies I had to increase the photos-imagesize a bit.

So if you like the idea, you may want to integrate it to your project.

__There are still some points where I'm not sure how to solve them in a more general way for a real release:__

- I think webdav support and matrix support wont't work at the same time at the moment because the webdav sync will overwrite downloaded pictures by the matrix client.
- You have to edit the matrix configuration file manually via ssh (webui would be much better I think).
- There must be a strategy how to delete old pictures because there is no "sync". For my first photoframe the idea is to show the newest N pictures and when you press on a button you can also see older pictures and if the storage size is getting low I will delete the oldest pictures.
- You get an errormessage when no webdav is configured maybe this should be configurable.
- I only modifed the raspberrypi3 config for now.

I'm still developing but the core feature is already working and I really appreciate input if someone likes it :)

kind regards

dirk

### CODE REVIEW

**Comment by avanc** [comment]
Wow, this is a cool idea. I'm using also Matrix (Element) daily :-)

As the changes are fundamental, my proposal is to integrate the changes into a branch and also create release out of this branch. So that one has to decide if the WebDAV solution or Matrix solution is wanted and flash the corresponding version.

@universalappfactory What Do you think? If technical possible (I didn't tried it before), I can give you write access to that branch to you can continue your work directly in that repository.

**Comment by universalappfactory** [comment]
Hi @avanc 

yes a seperate branch is a good way to go I think. Then the original image keeps to be small without all the dependencies for matrix.

I'm not entirely sure but I think specific access to a branch is only possible with pro or organization account:
https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

Maybe we have to stick to pull requests then.

**Comment by avanc** [comment]
As the thingOS updater always shows all releases of repository, I was afraid that someone accidentally selects the wrong version (either WebDAV or matrix) which would result into problems for sure.
I had a look into the [fwupdater](https://github.com/avanc/photOS/blob/master/board/common/overlay/sbin/fwupdate) but it doesn't seem to be easy to distinguish release somehow my name.

Thus, I decided to put your changes in a separate repository for now.
@universalappfactory I hope you are fine with this approach. I also gave you full access to that repository.

The first release is already in the build pipeline:
https://github.com/avanc/photOS-matrix/actions/runs/1674030489

**Comment by universalappfactory** [comment]
Hi @avanc ,

yes that's absolutely ok.
What's your preference regarding the matrix configuration documentation, should I put it in the wiki or just in the ReadMe from the new repository?

**Comment by avanc** [comment]
@universalappfactory
I would prefer to have the documentation in the photOS (main) wiki. From there we can than point to the separate repository. This way, the wiki would be always the starting point and the reader can than decide to go towards webdav or matrix.
And on the long term we might merge in future again.

**Pull request closed without merging**
